module AmazoneResponse
  class << self
    def list_inventory_supply
      <<-EOF
      <?xml version="1.0"?>
      <ListInventorySupplyResponse xmlns="http://mws.amazonaws.com/FulfillmentInventory/2010-10-01">
        <ListInventorySupplyResult>
          <InventorySupplyList>
            <member>
              <SellerSKU>SampleSKU1</SellerSKU>
              <ASIN>B00000K3CQ</ASIN>
              <TotalSupplyQuantity>20</TotalSupplyQuantity>
              <FNSKU>X0000000FM</FNSKU>
              <Condition>NewItem</Condition>
              <SupplyDetail/>
              <InStockSupplyQuantity>15</InStockSupplyQuantity>
              <EarliestAvailability>
                <TimepointType>Immediately</TimepointType>
              </EarliestAvailability>
            </member>
            <member>
              <SellerSKU>SampleSKU2</SellerSKU>
              <ASIN>B00004RWQR</ASIN>
              <TotalSupplyQuantity>0</TotalSupplyQuantity>
              <FNSKU>X00008FZR1</FNSKU>
              <Condition>UsedLikeNew</Condition>
              <SupplyDetail/>
              <InStockSupplyQuantity>0</InStockSupplyQuantity>
            </member>
          </InventorySupplyList>
        </ListInventorySupplyResult>
        <ResponseMetadata>
          <RequestId>e8698ffa-8e59-11df-9acb-230ae7a8b736</RequestId>
        </ResponseMetadata>
      </ListInventorySupplyResponse>
      EOF
    end

    def order_info
      <<-EOF
      <?xml version="1.0"?>
      <GetFulfillmentOrderResponse xmlns="http://mws.amazonaws.com/FulfillmentOutboundShipment/2010-10-01/">
        <GetFulfillmentOrderResult>
          <FulfillmentOrderItem>
            <member>
              <SellerSKU>SKU100</SellerSKU>
              <GiftMessage>giftwrap_message</GiftMessage>
              <SellerFulfillmentOrderItemId>merchant_order_item_id_2
              </SellerFulfillmentOrderItemId>
              <EstimatedShipDateTime>2014-01-03T07:07:53Z
              </EstimatedShipDateTime>
              <DisplayableComment>Example comment</DisplayableComment>
              <UnfulfillableQuantity>0</UnfulfillableQuantity>
              <CancelledQuantity>1</CancelledQuantity>
              <Quantity>5</Quantity>
              <EstimatedArrivalDateTime>2014-01-05T08:07:53Z
              </EstimatedArrivalDateTime>
              <PerUnitPrice>
                <CurrencyCode>JPY</CurrencyCode>
                <Value>2500</Value>
              </PerUnitPrice>
              <PerUnitTax>
                <CurrencyCode>JPY</CurrencyCode>
                <Value>5000</Value>
              </PerUnitTax>
            </member>
            <member>
              <SellerSKU>SKU101</SellerSKU>
              <GiftMessage>giftwrap_message</GiftMessage>
              <SellerFulfillmentOrderItemId>merchant_order_item_id_1
              </SellerFulfillmentOrderItemId>
              <EstimatedShipDateTime>2014-01-03T07:07:53Z
              </EstimatedShipDateTime>
              <DisplayableComment>Example comment
              </DisplayableComment>
              <UnfulfillableQuantity>2</UnfulfillableQuantity>
              <CancelledQuantity>1</CancelledQuantity>
              <Quantity>5</Quantity>
              <EstimatedArrivalDateTime>2014-01-05T08:07:53Z
              </EstimatedArrivalDateTime>
              <PerUnitPrice>
                <CurrencyCode>JPY</CurrencyCode>
                <Value>1000</Value>
              </PerUnitPrice>
              <PerUnitTax>
                <CurrencyCode>JPY</CurrencyCode>
                <Value>2000</Value>
              </PerUnitTax>
            </member>
          </FulfillmentOrderItem>
          <FulfillmentOrder>
            <ShippingSpeedCategory>ScheduledDelivery</ShippingSpeedCategory>
            <DeliveryWindow>
              <StartDateTime>2014-01-05T03:00:00Z</StartDateTime>
              <EndDateTime>2014-01-05T05:00:00Z</EndDateTime>
            </DeliveryWindow>
            <NotificationEmailList>
              <member>o8c2EXAMPLsfr7o@marketplace.amazon.com</member>
            </NotificationEmailList>
            <StatusUpdatedDateTime>2014-01-02T23:48:48Z
            </StatusUpdatedDateTime>
            <SellerFulfillmentOrderId>extern_id_1154539615776
            </SellerFulfillmentOrderId>
            <DestinationAddress>
              <PostalCode>153-0002</PostalCode>
              <Name>Amazon Taro</Name>
              <CountryCode>JP</CountryCode>
              <Line1>Meguro-ku Shimomeguro 12-34-56</Line1>
              <StateOrProvinceCode>Tokyo</StateOrProvinceCode>
              <Line2>XXX building 101</Line2>
            </DestinationAddress>
            <DisplayableOrderDateTime>2014-01-02T17:26:56Z
            </DisplayableOrderDateTime>
            <FulfillmentPolicy>FillOrKill</FulfillmentPolicy>
            <ReceivedDateTime>2014-01-02T17:26:56Z</ReceivedDateTime>
            <DisplayableOrderId>test_displayable_id</DisplayableOrderId>
            <DisplayableOrderComment>Sample comment
            </DisplayableOrderComment>
            <CODSettings>
              <IsCODRequired>true</IsCODRequired>
              <CODCharge>
                <Value>4000</Value>
                <CurrencyCode>JPY</CurrencyCode>
              </CODCharge>
              <CODChargeTax>
                <Value>300</Value>
                <CurrencyCode>JPY</CurrencyCode>
              </CODChargeTax>
              <ShippingCharge>
                <Value>1000</Value>
                <CurrencyCode>JPY</CurrencyCode>
              </ShippingCharge>
              <ShippingChargeTax>
                <Value>75</Value>
                <CurrencyCode>JPY</CurrencyCode>
              </ShippingChargeTax>
            </CODSettings>
            <FulfillmentOrderStatus>PROCESSING</FulfillmentOrderStatus>
          </FulfillmentOrder>
          <FulfillmentShipment>
            <member>
              <FulfillmentShipmentStatus>PENDING</FulfillmentShipmentStatus>
              <FulfillmentShipmentItem>
                <member>
                  <SellerSKU>SKU100</SellerSKU>
                  <SellerFulfillmentOrderItemId>merchant_order_item_id_2
                  </SellerFulfillmentOrderItemId>
                  <Quantity>2</Quantity>
                  <PackageNumber>0</PackageNumber>
                </member>
              </FulfillmentShipmentItem>
              <AmazonShipmentId>DnMDLWJWN</AmazonShipmentId>
              <ShippingDateTime>2014-01-03T07:00:00Z</ShippingDateTime>
              <FulfillmentCenterId>RNO1</FulfillmentCenterId>
              <EstimatedArrivalDateTime>2014-01-04T07:00:00Z
              </EstimatedArrivalDateTime>
            </member>
            <member>
              <FulfillmentShipmentStatus>SHIPPED</FulfillmentShipmentStatus>
              <FulfillmentShipmentItem>
                <member>
                  <SellerSKU>SKU101/SellerSKU>
                  <SellerFulfillmentOrderItemId>merchant_order_item_id_1
                  </SellerFulfillmentOrderItemId>
                  <Quantity>1</Quantity>
                  <PackageNumber>1</PackageNumber>
                </member>
              </FulfillmentShipmentItem>
              <AmazonShipmentId>DKMKLXJmN</AmazonShipmentId>
              <ShippingDateTime>2014-01-03T07:00:00Z</ShippingDateTime>
              <FulfillmentShipmentPackage>
                <member>
                  <TrackingNumber>93ZZ00</TrackingNumber>
                  <CarrierCode>UPS</CarrierCode>
                  <PackageNumber>1</PackageNumber>
                </member>
              </FulfillmentShipmentPackage>
              <FulfillmentCenterId>TST1</FulfillmentCenterId>
              <EstimatedArrivalDateTime>2014-01-05T07:00:00Z
              </EstimatedArrivalDateTime>
            </member>
          </FulfillmentShipment>
        </GetFulfillmentOrderResult>
        <ResponseMetadata>
          <RequestId>5e5e5694-8e76-11df-929f-87c80302f8f6</RequestId>
        </ResponseMetadata>
      </GetFulfillmentOrderResponse>
      EOF
    end
  end
end
